/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.*;
import javax.swing.JFrame;

public class CalculadoraVista extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public CalculadoraVista() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextPaneExpresion = new javax.swing.JTextPane();
        bttn1 = new javax.swing.JButton();
        bttn3 = new javax.swing.JButton();
        bttn2 = new javax.swing.JButton();
        bttn4 = new javax.swing.JButton();
        bttn5 = new javax.swing.JButton();
        bttn6 = new javax.swing.JButton();
        bttn9 = new javax.swing.JButton();
        bttn8 = new javax.swing.JButton();
        bttn7 = new javax.swing.JButton();
        bttnMasMenos = new javax.swing.JButton();
        bttn0 = new javax.swing.JButton();
        bttnPunto = new javax.swing.JButton();
        bttnCerrarParentesis = new javax.swing.JButton();
        bttnAbrirParentesis = new javax.swing.JButton();
        bttnSumar = new javax.swing.JButton();
        bttnRestar = new javax.swing.JButton();
        bttnVaciar = new javax.swing.JButton();
        bttnMultiplicar = new javax.swing.JButton();
        bttnDividir = new javax.swing.JButton();
        bttnIgual = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(TextPaneExpresion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, 240, 33));

        bttn1.setBackground(new java.awt.Color(255, 255, 255));
        bttn1.setText("1");
        bttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn1ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 40));

        bttn3.setBackground(new java.awt.Color(255, 255, 255));
        bttn3.setText("3");
        bttn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn3ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 40, 40));

        bttn2.setBackground(new java.awt.Color(255, 255, 255));
        bttn2.setText("2");
        bttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn2ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 40, 40));

        bttn4.setBackground(new java.awt.Color(255, 255, 255));
        bttn4.setText("4");
        bttn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn4ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 40, 40));

        bttn5.setBackground(new java.awt.Color(255, 255, 255));
        bttn5.setText("5");
        bttn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn5ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 40, 40));

        bttn6.setBackground(new java.awt.Color(255, 255, 255));
        bttn6.setText("6");
        bttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn6ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, 40));

        bttn9.setBackground(new java.awt.Color(255, 255, 255));
        bttn9.setText("9");
        bttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn9ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 40, 40));

        bttn8.setBackground(new java.awt.Color(255, 255, 255));
        bttn8.setText("8");
        bttn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn8ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 40, 40));

        bttn7.setBackground(new java.awt.Color(255, 255, 255));
        bttn7.setText("7");
        bttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn7ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, 40));

        bttnMasMenos.setBackground(new java.awt.Color(255, 255, 255));
        bttnMasMenos.setText("±");
        bttnMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnMasMenosActionPerformed(evt);
            }
        });
        getContentPane().add(bttnMasMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 40, 40));

        bttn0.setBackground(new java.awt.Color(255, 255, 255));
        bttn0.setText("0");
        bttn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn0ActionPerformed(evt);
            }
        });
        getContentPane().add(bttn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 40));

        bttnPunto.setBackground(new java.awt.Color(255, 255, 255));
        bttnPunto.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        bttnPunto.setText(".");
        bttnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(bttnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 40, 40));

        bttnCerrarParentesis.setBackground(new java.awt.Color(153, 153, 153));
        bttnCerrarParentesis.setText(")");
        bttnCerrarParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCerrarParentesisActionPerformed(evt);
            }
        });
        getContentPane().add(bttnCerrarParentesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 40, 40));

        bttnAbrirParentesis.setBackground(new java.awt.Color(153, 153, 153));
        bttnAbrirParentesis.setText("(");
        bttnAbrirParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAbrirParentesisActionPerformed(evt);
            }
        });
        getContentPane().add(bttnAbrirParentesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, 40));

        bttnSumar.setBackground(new java.awt.Color(153, 153, 153));
        bttnSumar.setText("+");
        bttnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSumarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, 40));

        bttnRestar.setBackground(new java.awt.Color(153, 153, 153));
        bttnRestar.setText("-");
        bttnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRestarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 40, 40));

        bttnVaciar.setBackground(new java.awt.Color(204, 204, 204));
        bttnVaciar.setText("VACIAR");
        bttnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVaciarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 90, 40));

        bttnMultiplicar.setBackground(new java.awt.Color(153, 153, 153));
        bttnMultiplicar.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        bttnMultiplicar.setText("*");
        bttnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 40, 40));

        bttnDividir.setBackground(new java.awt.Color(153, 153, 153));
        bttnDividir.setText("/");
        bttnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDividirActionPerformed(evt);
            }
        });
        getContentPane().add(bttnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 40, 40));

        bttnIgual.setBackground(new java.awt.Color(51, 153, 255));
        bttnIgual.setText("=");
        bttnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(bttnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 90, 40));

        lblResultado.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblResultado.setText("=");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 200, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setSize(new java.awt.Dimension(240, 120));
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 200, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //A continuación se encuentra lo que debe de hacer la interfaz al abrirse
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setBounds(200, 150, 500, 300);
        this.jTextArea1.setText("    -RESULTADOS-\n\n");
        
    }//GEN-LAST:event_formWindowOpened

    //A continuación se encuentra el manejo de todos los botones de la interfaz
    private void bttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn1ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"1");
    }//GEN-LAST:event_bttn1ActionPerformed

    private void bttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn2ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"2");
    }//GEN-LAST:event_bttn2ActionPerformed

    private void bttn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn3ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"3");
    }//GEN-LAST:event_bttn3ActionPerformed

    private void bttn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn4ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"4");
    }//GEN-LAST:event_bttn4ActionPerformed

    private void bttn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn5ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"5");
    }//GEN-LAST:event_bttn5ActionPerformed

    private void bttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn6ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"6");
    }//GEN-LAST:event_bttn6ActionPerformed

    private void bttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn7ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"7");
    }//GEN-LAST:event_bttn7ActionPerformed

    private void bttn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn8ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"8");
    }//GEN-LAST:event_bttn8ActionPerformed

    private void bttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn9ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"9");
    }//GEN-LAST:event_bttn9ActionPerformed

    private void bttn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn0ActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"0");
    }//GEN-LAST:event_bttn0ActionPerformed

    private void bttnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPuntoActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+".");
    }//GEN-LAST:event_bttnPuntoActionPerformed

    private void bttnMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMasMenosActionPerformed
        this.TextPaneExpresion.setText("0-("+this.TextPaneExpresion.getText()+")");
    }//GEN-LAST:event_bttnMasMenosActionPerformed

    private void bttnAbrirParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAbrirParentesisActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"(");
    }//GEN-LAST:event_bttnAbrirParentesisActionPerformed

    private void bttnCerrarParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCerrarParentesisActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+")");
    }//GEN-LAST:event_bttnCerrarParentesisActionPerformed

    private void bttnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSumarActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"+");
    }//GEN-LAST:event_bttnSumarActionPerformed

    private void bttnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRestarActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"-");
    }//GEN-LAST:event_bttnRestarActionPerformed

    private void bttnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMultiplicarActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"*");
    }//GEN-LAST:event_bttnMultiplicarActionPerformed

    private void bttnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDividirActionPerformed
        this.TextPaneExpresion.setText(this.TextPaneExpresion.getText()+"/");
    }//GEN-LAST:event_bttnDividirActionPerformed

    private void bttnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVaciarActionPerformed
        this.TextPaneExpresion.setText("");
        this.lblResultado.setText("");
    }//GEN-LAST:event_bttnVaciarActionPerformed

    private void bttnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnIgualActionPerformed

        String expresionInfija = this.TextPaneExpresion.getText();
        String resultado = "";
        
        
        if(Expresion.detectorErroresSintaxis(expresionInfija)) { //Checa la expresion que da el usuario para ver si tiene errores de sintaxis
            if(Expresion.detectorErroresMath(expresionInfija)){ //Checa la expresion que da el usuario para ver si tiene errores matemáticos
                //Esta linea hace todo el trabajo de la calculadora, convertir la expresion a postfijo para luego evaluarla
                resultado = Expresion.evaluarPostfija(Expresion.convertirPostfija(expresionInfija));

                this.lblResultado.setText("= "+resultado);
            }
            else {
                this.lblResultado.setText("ERROR MATEMATICO");
                resultado = "ERROR MATEMATICO";
            }
        }
        else {
                this.lblResultado.setText("ERROR DE SINTAXIS");
                resultado = "ERROR DE SINTAXIS";
        }
        
        this.jTextArea1.setText(this.jTextArea1.getText()+resultado+"\n");
    }//GEN-LAST:event_bttnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TextPaneExpresion;
    private javax.swing.JButton bttn0;
    private javax.swing.JButton bttn1;
    private javax.swing.JButton bttn2;
    private javax.swing.JButton bttn3;
    private javax.swing.JButton bttn4;
    private javax.swing.JButton bttn5;
    private javax.swing.JButton bttn6;
    private javax.swing.JButton bttn7;
    private javax.swing.JButton bttn8;
    private javax.swing.JButton bttn9;
    private javax.swing.JButton bttnAbrirParentesis;
    private javax.swing.JButton bttnCerrarParentesis;
    private javax.swing.JButton bttnDividir;
    private javax.swing.JButton bttnIgual;
    private javax.swing.JButton bttnMasMenos;
    private javax.swing.JButton bttnMultiplicar;
    private javax.swing.JButton bttnPunto;
    private javax.swing.JButton bttnRestar;
    private javax.swing.JButton bttnSumar;
    private javax.swing.JButton bttnVaciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
